using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using BestFlex.Application.Abstractions;
using BestFlex.Domain.Entities;
using BestFlex.Domain.Exceptions;

namespace BestFlex.Application.UseCases
{
    public interface IGenerateInvoiceFromOrderUseCase
    {
        Task<int> ExecuteAsync(GenerateInvoiceFromOrderCommand command, CancellationToken cancellationToken = default);
    }

    public class GenerateInvoiceFromOrderCommand
    {
        public int SalesOrderId { get; set; }
        public int GeneratedByUserId { get; set; }
        public DateTime InvoiceDate { get; set; }
        public DateTime? DueDate { get; set; }
        public string Notes { get; set; } = string.Empty;
        public string Currency { get; set; } = "USD";
    }

    public class GenerateInvoiceFromOrderUseCase : IGenerateInvoiceFromOrderUseCase
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IInvoiceNumberService _invoiceNumberService;

        public GenerateInvoiceFromOrderUseCase(IUnitOfWork unitOfWork, IInvoiceNumberService invoiceNumberService)
        {
            _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
            _invoiceNumberService = invoiceNumberService ?? throw new ArgumentNullException(nameof(invoiceNumberService));
        }

        public async Task<int> ExecuteAsync(GenerateInvoiceFromOrderCommand command, CancellationToken cancellationToken = default)
        {
            await _unitOfWork.BeginAsync();

            try
            {
                // Validate inputs
                if (command.SalesOrderId <= 0)
                    throw new DomainException("Sales order ID is required");

                if (command.GeneratedByUserId <= 0)
                    throw new DomainException("Generated by user ID is required");

                // In a real implementation, we would:
                // 1. Load sales order with lines from repository
                // 2. Validate order can be invoiced (must be Confirmed status)
                // 3. Generate sequential invoice number
                // 4. Create invoice with lines from sales order
                // 5. Post the invoice (makes it immutable)
                // 6. Link sales order to invoice
                // 7. Create audit entry
                // 8. Commit transaction

                // For now, demonstrate the transaction pattern with domain validation
                var invoiceNumber = await _invoiceNumberService.NextAsync(1); // Assuming CompanyId = 1

                // Create a test invoice to demonstrate domain rules
                var dueDate = command.DueDate ?? command.InvoiceDate.AddDays(30);
                var invoice = new Invoice(command.SalesOrderId, invoiceNumber, command.InvoiceDate, dueDate, command.Currency);

                // Add a test line (in real implementation, would copy from sales order)
                invoice.AddLine(1, "Test Product", 1, 100.00m, 0.1m);

                // Post the invoice (domain validation happens here)
                invoice.Post();

                // In Phase 5, we would:
                // - Save invoice to database
                // - Update sales order status to Invoiced
                // - Create audit trail entry
                // - Create accounting entries

                // Commit transaction
                await _unitOfWork.CommitAsync();

                // Return a mock invoice ID for now
                return new Random().Next(1000, 9999);
            }
            catch
            {
                await _unitOfWork.RollbackAsync();
                throw;
            }
        }
    }
}
